set preview_files true
set preview_images true
set open_all_images true
set preview_images_method ueberzug


set use_preview_script true
set draw_borders both
set column_ratios 3,3,4
default_linemode details
ext txt,md,wiki = vim "$@"
set colorscheme red


map gC cd ~/path/to/your/code
map gD cd ~/path/to/your/documents
map gdr cd ~/drobot
map gm cd ~/path/to/your/music
map gp cd ~/Pictures
map gv cd ~/path/to/your/videos
map s shell

map ,de console delete

ext png|jpg|gif, X, flag f = feh --. "$@"
mime ^video, X, flag f = mpv -- "$@"

